#spring:
#  profiles:
#    active: local # 기본 환경 선택

# local 환경
---
#spring:
#  profiles: local
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://suldiary.c4fqjnt58fk1.ap-northeast-2.rds.amazonaws.com:3306/sul_diary
#    username: highrima





